### PR TITLE
fix: set the gemspec version using the release tag value

### PR DESCRIPTION
**Pull request by Eazybright**
This PR updates the `release.yml` to include a step to automatically sets the version of the SDK to be published using the value of the release tag.

### CODE REVIEW

**Review by unicodeveloper — APPROVED** [review]

**Comment by Eazybright** [comment]
@unicodeveloper i've raised a PR for the fix: https://github.com/novuhq/novu-ruby/pull/47

**Comment by unicodeveloper** [comment]
@Eazybright I just tried it again and it failed.

This is the action log: https://github.com/novuhq/novu-ruby/actions/runs/6490687700/job/17626846860

So for some reason, it is still not using the new version number it is getting from the tags to publish to Rubygems. It's still using the gemspec file version number.

**Comment by unicodeveloper** [comment]
Never mind. I'll fix it. I think I have figured out what to do.

**Comment by unicodeveloper** [comment]
A new release has been tagged 🍾  🎊 . The process to release a new version now is:

- Update https://github.com/novuhq/novu-ruby/blob/main/lib/novu/version.rb with the new version that we want to tag
- Tag a new release on GitHub
- Workflow kicks in and automatically pushes the new version to Ruby gems.

**Comment by Eazybright** [comment]
> https://github.com/novuhq/novu-ruby/actions/runs/6490687700/job/17626846860

great work @unicodeveloper

**Pull request merged**
