### PR TITLE
Fix/add dependency to gemspec

### PR DESCRIPTION
**Pull request by Eazybright**

### CODE REVIEW

**Review by unicodeveloper — APPROVED** [review]

**Comment by clgiovannelli** [comment]
Sorry to bother you again but I get this error:

```shell
Could not find compatible versions

Because rails >= 7.1.0, < 7.1.1 depends on activesupport = 7.1.0
 and rails >= 7.1.1, < 7.1.2 depends on activesupport = 7.1.1,
 rails >= 7.1.0, < 7.1.2 requires activesupport = 7.1.0 OR = 7.1.1.
And because rails >= 7.1.2, < 7.1.3 depends on activesupport = 7.1.2,
 rails >= 7.1.0, < 7.1.3 requires activesupport = 7.1.0 OR = 7.1.1 OR = 7.1.2.
And because rails >= 7.1.3 depends on activesupport = 7.1.3
 and novu >= 1.2.0 depends on activesupport >= 6.1.7.2, < 7.A,
 rails >= 7.1.0 is incompatible with novu >= 1.2.0.
So, because Gemfile depends on novu >= 1.2.0
 and Gemfile depends on rails ~> 7.1.0,
 version solving has failed.
```

**Comment by Eazybright** [comment]
> @Eazybright what could really be the issue here? The activesupport is set to:
> 
> ```
> spec.add_dependency "activesupport", "~> 6.1", ">= 6.1.7.2"
> ```

activesupport "~> 6.1", ">= 6.1.7.2" can be explained as follows:
1. "~> 6.1" accept versions identical to >= 6.1 and < 6.2.
2. ">= 6.1.7.2" can accept version upwards but "rule 1" has made it useless because it pegs it to < 6.2.

So there is a conflict with the comparison.  

The fix should be `spec.add_dependency "activesupport", "~> 6.1", ">= 6.2"`

**Comment by Eazybright** [comment]
done https://github.com/novuhq/novu-ruby/pull/68

**Comment by unicodeveloper** [comment]
We just tagged a 1.3.0 release. Please can you try again with the new version? @clgiovannelli

**Pull request merged**
